[package]
name = "ent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
tracing-subscriber = "0.3.18"
anyhow = "1.0.86"
prost = "0.12.6"
prost-types = "0.12.6"
tonic = "0.11.0"
tonic-build = "0.11.0"
tracing = "0.1.40"
serde = "1.0.215"
config = "0.14.1"

[build-dependencies]
tonic-build = "0.11.0"
