version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ent
      POSTGRES_PASSWORD: ent_password
      POSTGRES_DB: ent
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ent"]
      interval: 5s
      timeout: 5s
      retries: 5

  ent:
    build: .
    ports:
      - "50051:50051"
    environment:
      - RUN_MODE=development
      - ENT_DATABASE_URL=postgres://ent:ent_password@postgres:5432/ent
      - ENT_SERVER_HOST=0.0.0.0
      # Variables for start.sh script
      - POSTGRES_USER=ent
      - POSTGRES_PASSWORD=ent_password
      - POSTGRES_DB=ent
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations

volumes:
  postgres_data: