name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ent
          POSTGRES_PASSWORD: ent_password
          POSTGRES_DB: ent
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: devenv

    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Start devenv shell
      run: devenv shell

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run cargo test
      run: devenv shell cargo test

    - name: Run integration tests
      run: |
        chmod +x scripts/test-ent.sh
        devenv shell ./scripts/test-ent.sh
      env:
        RUST_LOG: debug
        ENT_DATABASE_URL: postgres://ent:ent_password@localhost:5432/ent 